### ISSUE TITLE
Create a list of of movies that is able to be shared with other users

### ISSUE THREAD

**Issue by CC-Sev** [CS179K-Summer23/cs179-project-moviecritics#58]
For user story #9 and #50

**Comment by CC-Sev** [comment]
Test Case: Verify lists that are public are shown in other user accounts. Also, other users will not be able to see lists that are private to that user.

**Comment by hp6164** [comment]
Review by: @hp6164

**Comment by hp6164** [comment]
Add updates. Movie names are not being shown. Waiting for new function dependency to be implemented
